In [4]:
import csv

%precision 2

with open('mpg.csv') as csvfile:
    mpg=list(csv.DictReader(csvfile))
mpg[:10]

[OrderedDict([('', '1'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '1.8'),
              ('year', '1999'),
              ('cyl', '4'),
              ('trans', 'auto(l5)'),
              ('drv', 'f'),
              ('cty', '18'),
              ('hwy', '29'),
              ('fl', 'p'),
              ('class', 'compact')]),
 OrderedDict([('', '2'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '1.8'),
              ('year', '1999'),
              ('cyl', '4'),
              ('trans', 'manual(m5)'),
              ('drv', 'f'),
              ('cty', '21'),
              ('hwy', '29'),
              ('fl', 'p'),
              ('class', 'compact')]),
 OrderedDict([('', '3'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '2'),
              ('year', '2008'),
              ('cyl', '4'),
              ('trans', 'manual(m6)'),
              ('drv',

Extracting the column names

In [6]:
mpg[0].keys()

odict_keys(['', 'manufacturer', 'model', 'displ', 'year', 'cyl', 'trans', 'drv', 'cty', 'hwy', 'fl', 'class'])

#### Average value of City fuel economy:

In [15]:
sum([float(col['cty']) for col in mpg])/len(mpg)

16.86

#### Average value of Highway fuel economy:

In [16]:
sum([float(col['hwy']) for col in mpg])/len(mpg)

23.44

#### Unique number of cylinders in all cars

In [20]:
uniqueCyl=set([col['cyl'] for col in mpg])
uniqueCyl

{'4', '5', '6', '8'}

#### Grouping the cars based on number of cylinders and finding the avg city mpg for each group

In [23]:
CtyMpgByCyl=[]
for c in uniqueCyl:
    sumMpg=0
    CarsPcyl=0
    for col in mpg:
        if col['cyl'] == c:
            sumMpg +=float(col['cty'])
            CarsPcyl += 1
    CtyMpgByCyl.append((c,sumMpg/CarsPcyl))
    
CtyMpgByCyl
    

[('6', 16.22), ('4', 21.01), ('5', 20.50), ('8', 12.57)]

In [24]:
uniqueClass=set([col['class'] for col in mpg])
uniqueClass

{'2seater', 'compact', 'midsize', 'minivan', 'pickup', 'subcompact', 'suv'}

#### Grouping the cars based on number of classes and finding the avg Highway mpg for each class

In [30]:
HwyMpgByClass=[]
for c in uniqueClass:
    sumMpg=0
    CarsByClass=0
    for col in mpg:
        if col['class'] == c:
            sumMpg +=float(col['hwy'])
            CarsByClass += 1
    HwyMpgByClass.append((c,sumMpg/CarsByClass))
    
HwyMpgByClass

[('2seater', 24.80),
 ('subcompact', 28.14),
 ('compact', 28.30),
 ('pickup', 16.88),
 ('midsize', 27.29),
 ('minivan', 22.36),
 ('suv', 18.13)]

#### The Python Programming Language: Dates and Times

In [31]:
import datetime as dt
import time as tm

`time` returns the current time in seconds since the Epoch. (January 1st, 1970)

In [32]:
tm.time()

1580159431.12

Convert the current timrstamp to datetime format

In [35]:
dtnow=dt.datetime.fromtimestamp(tm.time())
dtnow

datetime.datetime(2020, 1, 27, 16, 20, 53, 296204)

In [37]:
dtnow.year, dtnow.month, dtnow.day, dtnow.hour, dtnow.minute, dtnow.second # get year, month, day, etc.from a datetime

(2020, 1, 27, 16, 20, 53)

`timedelta` is a duration expressing the difference between two dates.

In [38]:
delta = dt.timedelta(days = 100) # create a timedelta of 100 days
delta

datetime.timedelta(days=100)

In [39]:
today=dt.date.today()
today

datetime.date(2020, 1, 27)

In [40]:
today - delta

datetime.date(2019, 10, 19)

In [41]:
today > today-delta # compare dates

True

#### The Python Programming Language: Objects and map()

In [42]:
class student:
    program='Electrical And Computer Engineering'
    
    def set_name(self,new_name):
        self.name=new_name
    def set_location(self,new_location):
        self.location=new_location
student_1=student()
student_1.set_name("surya")
student_1.set_location("Erb St")
print("{} is a new student from the place {}".format(student_1.name,student_1.location))

surya is a new student from the place Erb St


Here is an example for using mapping function min between two lists.

In [45]:
store1 = [10.00, 11.00, 12.34, 2.34]
store2 = [9.00, 11.10, 12.34, 2.01]
cheapest = map(min, store1, store2)
cheapest

In [46]:
for item in cheapest:
    print(item)

9.0
11.0
12.34
2.01


#### The Python Programming Language: Lambda and List Comprehensions

In [47]:
my_function=lambda a,b,c:a+b
my_function

<function __main__.<lambda>(a, b, c)>


Let's iterate from 0 to 999 and return the even numbers.

In [48]:
even_numbers=[num for num in range(0,999) if num%2==0]
even_numbers

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198,
 200,
 202,
 204,
 206,
 208,
 210,
 212,
 214,
 216,
 218,
 220,
 222,
 224,
 226,
 228,
 230,
 232,
 234,
 236,
 238,
 240,
 242,
 244,
 246,
 248,
 250,
 252,
 254,
 256,
 258,
 260,
 262,
 264,
 266,
 268,
 270,
 272,
 274,
 276,
 278,
 280,
 282,
 284,
 286,
 288,
 290,
 292,
 294,
 296,
 298,
 300,
 302,
 304,
 306,
 308,
 310,
 312,
 314,
 316,
 318,
 320,
 322,
 324,
 326,
 328,
 330,
 332,
 334,
 336,
 338,
 340,
 342,
 344,
 346,
 348,
 350,


#### The Python Programming Language: Numerical Python (NumPy)

In [50]:
import numpy as np

Creating Array - Create a list and convert it to a numpy array


In [53]:
my_list=[1,2,3,4,5]
x=np.array(my_list)
x

array([1, 2, 3, 4, 5])


Or just pass in a list directly

In [55]:
y=np.array([6,7,8])
y

array([6, 7, 8])


Pass in a list of lists to create a multidimensional array.

In [58]:
m=np.array([[1,2,3],[4,5,6]])
m

array([[1, 2, 3],
       [4, 5, 6]])

In [60]:
#Use the shape method to find the dimensions of the array. (rows, columns)
m.shape

(2, 3)

`arange` returns evenly spaced values within a given interval.

In [70]:
n=np.arange(0,30,2)
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

`reshape` returns an array with the same data with a new shape.

In [71]:
n=n.reshape(3,5)
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])


`linspace` returns evenly spaced numbers over a specified interval.

In [68]:
o = np.linspace(0, 4, 9) # return 9 evenly spaced values from 0 to 4
o

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

`resize` changes the shape and size of array in-place.

In [69]:
o.resize(3,3)
o

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

`ones` returns a new array of given shape and type, filled with ones.